name: Telegram Calendar Bot


on:
  schedule:
    - cron: "0 5 * * *"   # 05:00 UTC = 08:00 GMT+3
    - cron: "0 11 * * *"  # 11:00 UTC = 14:00 GMT+3
  workflow_dispatch:      # для ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python calendar_bot.py
